# pyproject.toml
[project]
authors = [{name = "Ross J. Duff MSc", email = "rjdbcm@github.com"}]
dynamic = ["version"]
license = {file = "LICENSE"}
readme = "README.md"

[project.optional-dependencies]
dev = ["meson", "pre-commit", "pytest", "python-semantic-release"]

[tool.setuptools]
packages = ["lemprex"]

[build-system]
requires = ["mesonpep517", "ninja", "setuptools>=64", "setuptools_scm[toml]>=6.2"]
build-backend = "mesonpep517.buildapi"

[tool.mesonpep517.metadata]
requires-python = ">=3.9"
summary = 'Gets projects moving with stable draft code!'
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Natural Language :: English",
    "Intended Audience :: Developers",
    "Environment :: MacOS X",
    "Environment :: Win32 (MS Windows)",
    "Environment :: X11 Applications",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Software Development :: Interpreters",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[tool.semantic_release]
build_command = 'python -m build -w .'
major_on_zero = false
pre_commit_command = 'pre-commit autoupdate && python -m sigstore sign dist/*.whl'
tag_format = '{version}'
upload_to_repository = false
version_source = 'tag'
version_variable = '_scm_version.py:__version__,pyproject.toml:version'

[tool.setuptools_scm]
write_to = "_scm_version.py"

