name: Python package
'on':
  push:
    branches:
      - $default-branch
  pull_request:
    branches:
      - $default-branch
jobs:
  build:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        dev-namespace:
          - dist
          - docs
          - lint
          - test
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version:
          - '3.9'
          - '3.10'
          - '3.11'
      fail-fast: true
    steps:
      - uses: actions/checkout@v3
      - name: 'Set up Python ${{ matrix.python-version }}'
        uses: actions/setup-python@v3
        with:
          python-version: '${{ matrix.python-version }}'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .
      - name: Meson setup build
        run: |
          meson setup build -Ddev=enabled
      - name: 'Meson test suite ${{ matrix.dev-namespace }}'
        with:
          dev-namespace: '${{ matrix.dev-namespace }}'
        run: |
          meson test -C build --setup=${{ matrix.dev-namespace }}
