name: Python package
'on':
  push:
    branches:
      - $default-branch
  pull_request:
    branches:
      - $default-branch

concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: ${{ matrix.dev-namespace }} with ${{ matrix.py }} on ${{ matrix.os }}
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        ozi:
          - dist
          - docs
          - lint
          - test
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        py:
          - '3.9'
          - '3.10'
          - '3.11'
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Set up Python ${{ matrix.py }}'
        uses: actions/setup-python@v4
        with:
          python-version: '${{ matrix.py }}'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox-gh>=1.2
      - name: Meson setup build
        run: |
          tox -vv --notest
      - name: '${{ matrix.ozi }}'
        with:
          ozi: '${{ matrix.ozi }}'
        run: |
          tox --skip-pkg-install -- --setup=${{ matrix.ozi }}
