# Part of blastpipe.
# See LICENSE.txt in the project root for details.
name: OZI

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  checkpoint:
    name: OZI ${{ matrix.ozi }} with ${{ matrix.py }} on ${{ matrix.os }}
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        ozi:
          - dist
          - lint
          - test
        os:
          - ubuntu-latest
        py:
          - '3.10'
          - '3.11'
          - '3.12'
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: OZI-Project/checkpoint@0.1.2
        with:
          python-version: ${{ matrix.py }}
          suite: ${{ matrix.ozi }}
  release:
    needs: checkpoint
    runs-on: ubuntu-latest
    concurrency: release
    strategy:
      matrix:
        py:
          - 'py310'
          - 'py311'
          - 'py312'
      fail-fast: true
      max-parallel: 1
    outputs:
      drafted: ${{ steps.release.outputs.drafted }}
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: OZI-Project/release@0.1.13
        id: release
        with:
          python-dist: ${{ matrix.py }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
  publish:
    runs-on: ubuntu-latest
    needs: release
    if: needs.release.outputs.drafted == 'true'
    permissions:
      contents: write
      id-token: write
    steps:
    - uses: OZI-Project/publish@0.1.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}